"""Add workflow locking and override fields

Revision ID: 67f6f810f996
Revises: f889b1e96e1c
Create Date: 2026-01-19 13:52:18.353273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f6f810f996'
down_revision = 'f889b1e96e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_frozen', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('override_used', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('override_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('override_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('override_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'employees', ['locked_by'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['override_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('override_at')
        batch_op.drop_column('override_by')
        batch_op.drop_column('override_reason')
        batch_op.drop_column('override_used')
        batch_op.drop_column('is_frozen')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('locked_by')

    # ### end Alembic commands ###
