"""Add analysis fields to credit_assessments

Revision ID: e94ac605d88f
Revises: 67f6f810f996
Create Date: 2026-01-19 18:59:56.111091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94ac605d88f'
down_revision = '67f6f810f996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_health_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_reasons_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verification_notes_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_assessments', schema=None) as batch_op:
        batch_op.drop_column('verification_notes_json')
        batch_op.drop_column('risk_reasons_json')
        batch_op.drop_column('data_confidence')
        batch_op.drop_column('financial_health_score')

    # ### end Alembic commands ###
